version: '3.9'

services:
  frontend:
    image: "node:20.5.0-alpine"
    user: "node"
    container_name: 'frontend'
    restart: always
    working_dir: /home/frontend
    tty: true
    env_file:
      - .env_frontend
    volumes:
      - ./../../1.frontend:/home/frontend
    expose:
      - "3000"
    ports:
      - '3000:3000'
      - '24678:24678'
    networks:
      - red-apps
    command: ash -c "npm install && npm install tailwindcss @tailwindcss/vite && npm run dev"

  backend:
    image: "node:22.14.0-alpine"
    user: "root"
    restart: always
    container_name: 'backend'
    working_dir: /home/backend
    tty: true
    env_file:
      - .env_backend
    volumes:
      - './../../2.backend/:/home/backend'
    expose:
      - "8091"
    ports:
      - '8091:8091'
    networks:
      - red-apps
    command: ash -c "npm install && npm run start:dev"

  postgres:
    image: "postgres:15-alpine"
    container_name: postgres
    restart: always
    env_file:
      - .env_bbdd
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-apps

  nginx:
    image: 'nginx:alpine'
    container_name: 'nginx'
    restart: always
    tty: true
    networks:
      - red-apps
    ports:
      - '80:80'
      - '443:443'
    expose:
      - "80"
      - "443"
    volumes:
      - './nginx/:/etc/nginx/conf.d'

networks:
  red-apps:
    driver: bridge

volumes:
  postgres_data: