version: '3.9'

services:
  frontend:
    image: "node:20.5.0-alpine"
    user: "node"
    container_name: 'frontend'
    restart: always
    working_dir: /home/frontend
    tty: true
    environment:
      - NODE_ENV=development
      - FRONTEND_PORT=3000
      - FRONTEND_BASEPATH=/
      - BACKEND_URI=http://localhost:8091/api
      - NODE_OPTIONS=--openssl-legacy-provider
      - TZ=Europe/Madrid
    volumes:
      - ./../../1.frontend:/home/frontend
    expose:
      - "3000"
    ports:
      - '3000:3000'
    networks:
      - red-apps
    command: ash -c "npm install && npm start"

  backend:
    image: "node:22.14.0-alpine"
    user: "root"
    restart: always
    container_name: 'backend'
    working_dir: /home/backend
    tty: true
    env_file:
      - .env
    volumes:
      - './../../2.backend/:/home/backend'
    expose:
      - "8091"
    ports:
      - '8091:8091'
    networks:
      - red-apps
    command: ash -c "npm install && npm run start:dev"

  postgres:
    image: "postgres:15-alpine"
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_HOST=172.20.118.90 # Can change once we restart WSL
      - POSTGRES_DB=mindnestdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - TZ=Europe/Madrid
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red-apps

  nginx:
    image: 'nginx:alpine'
    container_name: 'nginx'
    restart: always
    tty: true
    networks:
      - red-apps
    ports:
      - '80:80'
      - '443:443'
    expose:
      - "80"
      - "443"
    volumes:
      - './nginx/:/etc/nginx/conf.d'

networks:
  red-apps:
    driver: bridge

volumes:
  postgres_data: